version: "3.8"

services:
    mariadb:
        image: mariadb:10.5
        container_name: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: admin123
            MYSQL_DATABASE: payment
        ports:
            - "3306:3306"
        volumes:
            - mariadb_data:/var/lib/mysql
        networks:
            - app_network

    app:
        build:
            context: .
            target: build #production
        depends_on:
            - mariadb
        networks:
            - app_network
        ports:
            - 3000:3000
        volumes:
            - ./:/app
            - /app/node_modules

networks:
    app_network:
        driver: bridge

volumes:
    mariadb_data:
        driver: local
