#Build
FROM node:latest AS build

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build && npx prisma generate

CMD ["npm", "run", "dev"]

#Production
FROM node:latest AS production

WORKDIR /app

COPY package.json .

RUN npm install --only=production && npx prisma generate

COPY --from=build /app/dist ./dist

CMD ["npm", "run", "start"]